# Generated by Django 2.2.26 on 2022-06-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
